### ISSUE TITLE
Support Fastify v5

### ISSUE THREAD

**Issue by strmer15** [nearform/fastify-jwt-jwks#26]
Thanks for this project!

We're trying to update to Fastify v5, but this package throws an error saying it can only work with v4. Could you update it to also provide support for Fastify v5?

```
FastifyError: fastify-plugin: fastify-jwt-jwks - expected '4.x' fastify version, '5.0.0' is installed
```

**Comment by robcresswell** [comment]
Hello! I just wanted to check where this issue is internally. Is this something one of the nearform folks is planning on picking up? Would you like it fixed as an external contribution? Just dont want to step on anyones toes, but equally quite keen to see this doesnt get stuck 😇

**Comment by robcresswell** [comment]
No expectations from me at all, I'm grateful this was built in the first place

**Comment by robcresswell** [comment]
Awesome, I will sit down and take a look this weekend

**Comment by robcresswell** [comment]
Ah I'd just forked it and started working an hour or so ago. thanks for addressing this! Sorry I wasnt any help

**Comment by simoneb** [comment]
@robcresswell you will have noticed already, but the release was done already

**Comment by robcresswell** [comment]
@simoneb thank you very much!
